# -*- coding: utf-8 -*-
"""3.sort.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19FFXqGb0KNMBtMj16Ag-w-SHMZYtQC2K
"""

# sort

def sort(x):
    i_last = len(x) - 1

    while i_last > 0:
        # 가장 큰값을 찾는다.
        v_max = -99999
        v_idx = 0
        for j in range(i_last + 1):
            if x[j] > v_max:
                v_max = x[j]
                v_idx = j
        
        # 가장 큰 값을 맨 뒤로 옮긴다. swap.
        v_last = x[i_last]
        x[i_last] = v_max
        x[v_idx] = v_last
        i_last -= 1

    return x

A = [4, 1, 6, 5, 7, 9, 3, 2, 8]
print(sort(A))

