# -*- coding: utf-8 -*-
"""4.sort(recursion).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1njMxfl5H4dWNm7JH4lzCHEXL0HEdOsn-
"""

# sort : using recursion

def find_max(x):
    v_max = -99999
    idx = 0
    for i in range(len(x)):
        if x[i] > v_max:
            v_max = x[i]
            idx = i
    return idx

def swap(x, i, k):
    tmp = x[k]
    x[k] = x[i]
    x[i] = tmp

def sort(x):
    if len(x) < 1:
        return
    else:
        idx = find_max(x)
        result[len(x) - 1] = x[idx]
        swap(x, idx, len(x) - 1)
        sort(x[: (len(x) - 1)])

A = [4, 1, 6, 5, 7, 9, 3, 2, 8]
result = [0] * len(A)
sort(A)
print(result)

